#!/usr/bin/env php
<?php
define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class); // console 控制台

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput, // 参数输入
    new Symfony\Component\Console\Output\ConsoleOutput // 输出
);

$kernel->terminate($input, $status); // 

exit($status); // 退出状态码
